### ISSUE TITLE
kafka chart needs to support dedicated roles

### ISSUE THREAD

**Issue by jeffmontagna** [terascope/helm-charts#14]
## Background

- The kafka chart `process.roles` for each pod is broker and controller.  In a production scenario it is desirable to have pods dedicated to the controller role in much the same way as the zookeeper cluster and the brokers only having the broker role. 
https://github.com/terascope/helm-charts/blob/bdfce46bf791681b7bfdf21c429695873d5137ae/charts/kafka/templates/_helpers.tpl#L61

- The number of replicas for pods with the broker role should be independent from the controller pods, i.e. a cluster with 12 brokers and 3 controllers.
- The chart should be able to still have a pod perform both roles.
- The controller and broker roles should be able to have different storage class/size and resource requests/limits.
 
## Implementation 
- TBD
- One method would be using an umbrella chart `kafka-cluster` that sources the `kafka` chart and defines the roles. 
```yaml
global:
   name: kafka-cluster1
kafka-controller:
   replicas: 3
   roles: controller
kafka-broker:
   replicas: 12
   roles: broker  
```

**Comment by busma13** [comment]
I began playing around with an umbrella chart. It looks like the Chart.yaml can't have 2 dependencies on the same chart with the same name, but the name needs to match the chart name.

Bad Chart.yaml:

```
apiVersion: v1
description: Cluster of Apache Kafka brokers and controllers.
name: kafka-cluster
version: 1.0.0
dependencies:
  - name: kafka
    version: 1.2.0
    repository: https://terascope.github.io/helm-charts/
  - name: kafka
    version: 1.2.0
    repository: https://terascope.github.io/helm-charts/
```

We can create wrapper charts that will in turn use the kafka chart as a dependency.

```
apiVersion: v1
description: Cluster of Apache Kafka brokers and controllers.
name: kafka-cluster
version: 0.1.0
dependencies:
  - name: broker-controller-wrapper
    version: 0.1.0
    repository: https://terascope.github.io/helm-charts/
  - name: broker-only-wrapper
    version: 0.1.0
    repository: https://terascope.github.io/helm-charts/
  - name: controller-only-wrapper
    version: 0.1.0
    repository: https://terascope.github.io/helm-charts/
```

I don't know if the duplication of all the resources when using an umbrella chart is necessary. Maybe we would need to disable some of them?

Austin and I discussed another option. We could modify the current kafka chart to create multiple statefulsets for broker, controller, or combo roles. We would probably want to create separate services for each role as well. I'm not sure which route will be easier in the short or long run. This is the route that bitnami took with their chart. They have A LOT of checks to see what roles are present, which kind of scares me.
